from ollama import ChatResponse, Client #REMOVED OllamaError 
from RT import Update  #Let either CLI agent loop or Package agent loop use Update.package_update() as tool for agent.
import requests
import json

#===TOOL REGISTRY=== (needed incase the LLM calls functions we DO NOT want to call. Is a security mesure.)
TOOL_REGISTRY = {
    "package_update": Update.package_update
}

#===agent system prompt (Prompt generated by LLM)===
SYSTEM_PROMPT = ('''
You are a restricted assistant that operates in TWO MODES:

----------------------------------------
MODE 1 — TOOL CALLING (DEFAULT)
----------------------------------------

Your primary job is to call the function:

Update.package_update(...)

When NO tool result is present in the conversation:

1. ALWAYS respond with a function call in this exact format:

CALL_FUNCTION:
Update.package_update(
    q="<string>",
    minScore=<int>,
    minComments=<int>,
    limit=<int>,
    page=<int>,
    fields="<string>",
    ascending=<int>
)
                 
2. DO NOT:
- Answer questions
- Explain anything
- Add commentary
- Summarize
- Ask follow-up questions

3. Parameter rules:
- If no parameters → use defaults
- If partial → fill missing with defaults

DEFAULTS:
- q="programming, Python"
- minScore=50
- minComments=10
- limit=25
- page=2
- fields="url,score,tag,title,subreddit,author_description"
- ascending=1

4. If the request is unrelated:
→ STILL call the function with defaults

----------------------------------------
MODE 2 — SUMMARIZATION MODE
----------------------------------------

If a TOOL RESULT is present in the conversation (output from Update.package_update):

1. DO NOT call the function again.

2. Instead:
- Summarize the tool result clearly and concisely
- Highlight key posts, trends, or important information
- Keep it structured and readable

3. You are now allowed to:
- Interpret results
- Summarize data

4. DO NOT:
- Call any function again
- Output CALL_FUNCTION

----------------------------------------
DETECTION RULE
----------------------------------------

If the latest message in the conversation contains raw data returned from a tool:
→ Switch to SUMMARIZATION MODE

Otherwise:
→ Stay in TOOL CALLING MODE

----------------------------------------
INPUT INTERPRETATION
----------------------------------------

Extract parameters ONLY if explicitly mentioned:
- "high score" → increase minScore
- "more posts" → increase limit
- "descending" → ascending=0
- "python subreddit" → q="python"

If unclear → use defaults

----------------------------------------
EXAMPLE FLOW
----------------------------------------

User → "Show me Python posts"

→ You respond:
CALL_FUNCTION: Update.package_update(...)

(System executes tool and appends result)

→ You respond:
"Here are the key highlights from the results: ..."
''')

#Testing of python package functions.  
#Should have a function that is the main() loop.
 
class AgentUpdate:
    @staticmethod
    def agent_update_conversation():
        #Initial stage for agent.
        
        #Check whether ollama is running before conversation loop.
        if not AgentUpdate.is_ollama_running():
            print("Ollama is not running.")
            print("Please start it by running: ollama serve")
            print("Make sure gemma3 is downloaded: ollama pull gemma3")
            return
        
        print("Ollama is running. Starting agent conversation...")

        #Initialize client application (includes agent). <<<<<<<

        

        user_input = str(input("Ask the agent about any updates on Reddit related to programming or Python. Type 'exit' to quit.\n"))

        client = Client()
        messages = [
                {
                    'role' : 'system',
                    'content' : SYSTEM_PROMPT
                },
                {
                    'role' : 'user',
                    'content' : user_input
                }
            ]
        
        
        #Finish initialization.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        
        while user_input.lower() != 'exit' : 
            try:
                response = client.chat(
                    model='llama3.2:3b',      #CHANGE: model='gemma3:latest' -> model='llama3.2:3b'
                    messages=messages, 
                    tools=[Update.package_update],
                    stream=False, 
                    think=False
                ) 
                #NOTES:message follows the format of {'role': 'assistant', 'content': '...', 'tool_calls': [...]} even the returned content from the tool is in the same format. 
                #NOTES:Hence we can append the returned content from the tool call to the messages list and it will be processed by the model in the next loop iteration.
                ai_message = response.message
                
                messages.append(ai_message) 
                #NOTES:The ollama agent will NOT run functions, but supply a list in it's dictionary format ['tool_calls'] which includes the functions it WANTS to call. 
                #NOTES:Therefore, we can run the functions ourselves. STILL acts as a dynamic agent!!!
                #NOTES:`tool_calls` has the format of [{'function': {'name': 'package_update', 'arguments': {...}}}, ...] 
                #NOTES:We need to extract the function NAME, extract its ARGUMENTS, and RUN. 
                #NOTES:Extract arguments for function use with `package_update(**kwargs)` == `package_update(q=5, minScore=10, etc.)`
                if ai_message.tool_calls:
                    for tool in ai_message.tool_calls:
                        function_name = tool.function.name
                        function_args = tool.function.arguments
                        if function_name in TOOL_REGISTRY:
                            # Run the actual Python function with the AI-chosen arguments.
                            # **function_args unpacks the dict as keyword arguments.
                            # e.g. package_update(**{"q": "Python"}) → package_update(q="Python")
                            tool_result = TOOL_REGISTRY[function_name](**function_args)         #< Dict TOOL_REGISTRY holds function references. If we use the correct key, it will return the function reference, then we can call with parameters from `function_args`.
                            messages.append({
                                "role": "tool",
                                "content": str(tool_result)
                        })# Append the function result to the conversation for the agent to see in the next iteration.
                        else:
                            # The AI asked for a function we don't allow — block it
                            tool_result = f"Error: '{function_name}' is not an approved function."
                            messages.append({
                                "role": "tool",
                                "content": str(tool_result)
                       })    
                    continue
                print(response.message.content)
            except Exception as e: #OllamaError -> Exception
                print(f"Error during agent conversation: {e}")
                return
                #FIX: >>"Python functions NEED to follow Google style docstrings to be CONVERTED -> to an Ollama TOOL." 
                #REPLACE print(response['message']['content']) -> print(response.message.content) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<       
            user_input = str(input("Ask the agent about any updates on Reddit related to programming and Python. Type 'exit' to quit.\n"))
    
        print("Exiting agent conversation.")
            
        


    #Returns True/False if ollama is running. Used to check if agent can run or not. === Useful for CLI agent to check before starting loop.
    @staticmethod
    def is_ollama_running():
        try:
            res = requests.get("http://localhost:11434/api/tags", timeout=2)
            return res.status_code == 200
        except requests.exceptions.RequestException:
            return False

def main():
    AgentUpdate.agent_update_conversation()

#Fix: Instanciate the agent and let it dynamically handle functions as "tools"
if __name__ == "__main__":
    main()





